root/files/resource/Sql/sqlserver/AsyncProcessingService/AsyncProcessingServiceSelect.sql
root/files/resource/Sql/sqlserver/AsyncProcessingService/AsyncProcessingServiceStatusUpdate.sql
root/programs/C#/Frameworks/Infrastructure/Framework/AsyncProcessingService/AsyncProcessingServiceParameterValue.cs
root/programs/C#/Frameworks/Infrastructure/Framework/AsyncProcessingService/LayerB.cs
root/programs/C#/Frameworks/Infrastructure/Framework/AsyncProcessingService/LayerD.cs
root/programs/C#/Frameworks/Infrastructure/ServiceInterface/AsyncProcessingService/AsyncProcessingService.cs
root/programs/C#/Frameworks/Infrastructure/ServiceInterface/AsyncProcessingService/TMInProcessDefinition.xml
root/programs/C#/Frameworks/Infrastructure/ServiceInterface/AsyncProcessingService/TMProtocolDefinition.xml

1.Implemented main thread and worker thread functionality  in AsyncProcessingService.cs.
2.Implemented select functionlaity in AsyncProcessingService.cs.
3.Modified in LayerB/LayerD.

Did code changes in .Async processing service

---

root/programs/C#/Frameworks/Infrastructure/ServiceInterface/AsyncProcessingService/AsyncProcessingService.cs
root/programs/C#/Frameworks/Infrastructure/ServiceInterface/AsyncProcessingService/app.config

1) Did code changes to break the main thread when service failed(i.e. unexpected exceptions)
2) Modified the incorrect log file name in the .config file

Modified the code of AsyncProcessingService project

---

root/programs/C#/Frameworks/Infrastructure/Framework/Presentation/BaseController.cs
root/programs/C#/Frameworks/Infrastructure/Framework/Util/FxCmnFunction.cs
root/programs/C#/Frameworks/Infrastructure/Framework/Util/FxLiteral.cs
root/programs/C#/Samples/WebApp_sample/ProjectX_sample/Aspx/testFxLayerP/normal/testScreen2.aspx
root/programs/C#/Samples/WebApp_sample/ProjectX_sample/Aspx/testFxLayerP/normal/testScreen2.aspx.cs
root/programs/C#/Samples/WebApp_sample/ProjectX_sample/Framework/Js/ie_key_event.js
root/programs/C#/Samples/WebApp_sample/ProjectX_sample/app.config

Did correct indentation problem.

Text box event handler

---

root/programs/C#/Frameworks/Infrastructure/Business/AsyncProcessingService/AsyncProcessingServiceParameterValue.cs
root/programs/C#/Frameworks/Infrastructure/ServiceInterface/AsyncProcessingService/AsyncProcessingService.cs
root/programs/C#/Frameworks/Infrastructure/ServiceInterface/AsyncProcessingService/AsyncProcessingService.csproj
root/programs/C#/Frameworks/Infrastructure/ServiceInterface/AsyncProcessingService/app.config

1) Modfied enum values data type to string values
2) Implemented code for retrieving values from enum
3) Changes target framework to 4.0
4) Fixed copy progress issues

Modified enum code to store string values

---

root/programs/C#/Frameworks/Infrastructure/Business/Business/_3TierEngine.cs
root/programs/VB/Frameworks/Infrastructure/Business/Business/_3TierEngine.vb

Recreated branch and created new pull request

Recreated branch and created new pull request

---

root/files/resource/Sql/sqlserver/AsyncProcessingService/UpdateTaskFail.sql
root/files/resource/Sql/sqlserver/AsyncProcessingService/UpdateTaskRetry.sql
root/programs/C#/Frameworks/Infrastructure/Business/AsyncProcessingService/AsyncProcessingServiceParameterValue.cs
root/programs/C#/Frameworks/Infrastructure/Business/AsyncProcessingService/AsyncProcessingServiceReturnValue.cs
root/programs/C#/Frameworks/Infrastructure/Business/AsyncProcessingService/LayerD.cs
root/programs/C#/Frameworks/Infrastructure/ServiceInterface/AsyncProcessingService/AsyncProcessingService.cs
root/programs/C#/Frameworks/Infrastructure/ServiceInterface/AsyncProcessingService/MSGDefinition.xml
root/programs/C#/Frameworks/Infrastructure/ServiceInterface/AsyncProcessingService/ServiceInstaller.cs

1) Added new variable "_workerThreadCount" to handle the worker thread and to resolve OnStop event error, because thread pool may be shared by other tasks, such as .NET runtime
2) Did code modification related to log information, for debugging purpose

Modified the following code in the AsyncProcessingService

---

CONTRIBUTING.md
root/programs/C#/Frameworks/Infrastructure/Business/Dao/CmnDao.cs
root/programs/C#/Frameworks/Infrastructure/Public/Db/BaseDam.cs
root/programs/C#/Frameworks/Infrastructure/Public/Db/DamDB2/DamDB2.cs
root/programs/C#/Frameworks/Infrastructure/Public/Db/DamHiRDB/DamHiRDB.cs
root/programs/C#/Frameworks/Infrastructure/Public/Db/DamMySQL/DamMySQL.cs
root/programs/C#/Frameworks/Infrastructure/Public/Db/DamODBC.cs
root/programs/C#/Frameworks/Infrastructure/Public/Db/DamOLEDB.cs
root/programs/C#/Frameworks/Infrastructure/Public/Db/DamOraClient.cs
root/programs/C#/Frameworks/Infrastructure/Public/Db/DamOraOdp/DamOraOdp.cs
root/programs/C#/Frameworks/Infrastructure/Public/Db/DamPstGrS/DamPstGrS.cs
root/programs/C#/Frameworks/Infrastructure/Public/Db/DamSqlSvr.cs

Modified SetCommandTimeout method parameter to this._cmd instead of IDbCommand in DamODBC.cs and DamOLEDB.cs

Modified SetCommandTimeout method parameter

---

root/programs/C#/Frameworks/Infrastructure/ServiceInterface/AsyncProcessingService/SampleLogConfAsyncProcessingService.xml

Modified the code XML log file, as discussed in the meeting

Modified the code XML log file, as discussed in the meeting

---

root/files/tools/DGenTemplates/DaoTemplate.cs
root/files/tools/DGenTemplates/DaoTemplate.vb
root/programs/VB/Frameworks/Infrastructure/Business/Dao/CmnDao.vb

1) Replaced SqlCommand property with IDbCommand property in SetCommandTimeout method in the classes DaoTemplate.cs, DaoTemplate.vb and CmnDao.vb

Did code review changes

---

root/files/resource/Sql/sqlserver/AsyncProcessingService/SelectTask.sql
root/files/resource/Sql/sqlserver/AsyncProcessingService/StopAllTask.sql
root/files/resource/Sql/sqlserver/AsyncProcessingService/UpdateTaskCommand.sql
root/files/resource/Sql/sqlserver/AsyncProcessingService/UpdateTaskStart.sql
root/programs/C#/Frameworks/Infrastructure/Business/AsyncProcessingService/LayerB.cs
root/programs/C#/Frameworks/Infrastructure/Business/AsyncProcessingService/LayerD.cs
root/programs/C#/Frameworks/Infrastructure/Business/Business.csproj
root/programs/C#/Frameworks/Infrastructure/ServiceInterface/AsyncProcessingService/AsyncProcessingService.cs

1) Implemented code to update stop command to all the running asynchronous task
2) Modified code to reset Exception information, before starting asynchronous task 
3) Added SQL query file to update stop command to all the running asynchronous task
4) Changed name of SQL file UpdateTaskAbort.sql to UpdateTaskCommand.sql, for better naming convention

Modified the following changes, according to new CRs of OnStop method  

---

root/programs/C#/Frameworks/Infrastructure/ServiceInterface/AsyncProcessingService/MSGDefinition.xml
root/programs/C#/Frameworks/Infrastructure/ServiceInterface/AsyncProcessingService/app.config

1) Added user programs error message information in the embedded XML file
2) Added config parameter to sleep thread while doing copy job

Modified the following according to CR and Bugs

---

root/programs/C#/Frameworks/Tools/DaoGen_Tool/Form2.cs

1)Added <Else></Else> tag in create string method and ReplaceSQL method to fix the bug 'DynInsParameter of dynamic insert'

Fixed the bug 'DynInsParameter of dynamic insert'.

---

root/files/resource/Sql/sqlserver/AsyncProcessingService/SelectTask.sql
root/programs/C#/Frameworks/Infrastructure/Business/AsyncProcessingService/LayerB.cs
root/programs/C#/Frameworks/Infrastructure/Business/AsyncProcessingService/LayerD.cs
root/programs/C#/Frameworks/Infrastructure/ServiceInterface/AsyncProcessingService/AsyncProcessingService.cs
root/programs/C#/Frameworks/Infrastructure/ServiceInterface/AsyncProcessingService/MSGDefinition.xml

Added user name(email-id) and asynchronous processing task ID to the arguments of user information

Modified the following code for the failure analysis

---

root/programs/C#/Frameworks/Infrastructure/Business/Business.csproj
root/programs/C#/Frameworks/Infrastructure/Business/Business/MyApsBaseLogic.cs
root/programs/C#/Samples/AsyncSvc_sample/AsyncSvc_sample/LayerB.cs

1) Added new class file "MyApsBaseLogic" in business project
2) Implemented code to create two dams, one for ABT asynchronous business task and another for AMT asynchronous management task
3) Resolved transaction timeout issue by using DamKeyForABT and DamKeyForAMT properties, in the AsyncSvc_sample project

Modified following code in the Business and AsyncSvc_sample project

---

root/programs/C#/Samples/WebApp_sample/ProjectX_sample/Framework/Js/common.js

Added condition code to detect IE-9, IE-10 and IE-11, to suppress double transmission.

Added condition code to detect IE-9, IE-10 and IE-11, to suppress double transmission.

---

root/programs/C#/Tests/BDLayer.Test/BDLayer.Test.nunit
root/programs/C#/Tests/BDLayer.Test/CRUDTest.cs

Did test code developemnt for the methods SelectAll_DSQL, SelectAll_DR, Select, Insert, Update and Delete in BDLayer

BDLayer Test code development

---

root/programs/C#/Frameworks/Infrastructure/Framework/Util/FxHttpSessionIndex.cs

Added constant string to store dummy key and value in FxHttpSessionIndex.cs.

Did Enhancement of BaseController

---

root/programs/C#/z_Common2.bat
root/programs/VB/z_Common2.bat
root_easysetup/programs/C#/z_Common2.bat
root_easysetup/programs/VB/z_Common2.bat

Specified disk name along with program files directory in root and root_easysetup.

---

root_easysetup/programs/C#/Frameworks/Infrastructure/Framework/Util/FxHttpSessionIndex.cs
root_easysetup/programs/C#/Frameworks/Infrastructure/ServiceInterface/AsyncProcessingService/AsyncProcessingService.cs
root_easysetup/programs/C#/Frameworks/Infrastructure/ServiceInterface/AsyncProcessingService/TMInProcessDefinition.xml
root_easysetup/programs/C#/Samples/AsyncSvc_sample/TestAsyncSvc_Sample/app.config
root_easysetup/programs/C#/Tests/BDLayer.Test/BDLayer.Test.nunit
root_easysetup/programs/C#/Tests/BDLayer.Test/CRUDTest.cs

Fixed the below pointed out
OpenTouryoProject/OpenTouryo#117 (comment)

root_easysetup Pointedout in merge

---

root/programs/C#/Frameworks/Infrastructure/Public/Util/Latebind.cs

Reverts SymphonyTeleca/OpenTouryo#83

Revert "Fixed the exception in Latebind.InvokeMethod method"

---

root/programs/C#/z_Common2.bat
root/programs/VB/z_Common2.bat
root_easysetup/programs/C#/z_Common2.bat
root_easysetup/programs/VB/z_Common2.bat

Removed the space added between the build file path

Improved build system by removing the space added between the build file path

---

root/files/resource/Screen/ProductsDetail.aspx.cs
root/files/resource/Screen/my_tableDetail.aspx.cs
root/files/tools/DGenTemplates/Detail.aspx.cs
root/files/tools/DGenTemplates/Detail.aspx.vb
root/files/tools/DGenTemplates/_Screen_Detail.aspx.cs
root/files/tools/DGenTemplates/_Screen_Detail.aspx.vb
root/programs/C#/Samples/WebApp_sample/ProjectX_sample/Aspx/sample/3Tier/ProductsDetail.aspx.cs
root/programs/VB/Samples/WebApp_sample/ProjectX_sample/Aspx/sample/3Tier/ProductsDetail.aspx.vb

Modified ReadOnly property of the primary key column textbox to true.
https://github.com/OpenTouryoProject/OpenTouryo/issues/120

Modified ReadOnly property of the primary key column textbox to true.

---

root/programs/C#/Samples/WebApp_sample/ProjectX_sample/Framework/Js/common.js
root/programs/VB/Samples/WebApp_sample/ProjectX_sample/Framework/Js/common.js

Changed interval in method window.setInterval(HttpPing, 5000)

Changed interval in method window.setInterval(HttpPing, 5000)

---

root/programs/C#/Frameworks/Tools/DaoGen_Tool/Form2.ja-JP.resx
root/programs/C#/Frameworks/Tools/DaoGen_Tool/Form2.resx

Corrected the DaoGen tool captions
https://github.com/OpenTouryoProject/OpenTouryo/issues/139#issuecomment-171937652

Corrected the DaoGen tool captions

---

root/programs/C#/Frameworks/Infrastructure/Public/Str/CustomEncode.cs

Modified the method UrlEncode to call the method Uri.UnescapeDataString
https://github.com/OpenTouryoProject/OpenTouryo/issues/136#issuecomment-178955122

Modified the method UrlEncode to call the method Uri.UnescapeDataString

---

root/programs/C#/Samples/WebApp_sample/ProjectX_sample/Aspx/Framework/DialogFrame.htm

Fixed the issue 'IE11IgnoresDialogWidth-Height'
https://github.com/OpenTouryoProject/OpenTouryo/issues/74

Fixed the issue 'IE11IgnoresDialogWidth-Height'

---

root/programs/VB/Frameworks/Infrastructure/Business/Presentation/MyBaseController.vb
root/programs/VB/Frameworks/Infrastructure/CustomControl/Control/WebCustomImageButton.vb
root/programs/VB/Frameworks/Infrastructure/CustomControl/Control/WebCustomImageMap.vb
root/programs/VB/Samples/WebApp_sample/ProjectX_sample/Aspx/Common/sampleScreen.master
root/programs/VB/Samples/WebApp_sample/ProjectX_sample/Aspx/Common/testAspNetAjaxExtension_Separate.master
root/programs/VB/Samples/WebApp_sample/ProjectX_sample/Aspx/Common/testAspNetAjaxExtension_Single.master
root/programs/VB/Samples/WebApp_sample/ProjectX_sample/Aspx/Common/testBlankScreen.master
root/programs/VB/Samples/WebApp_sample/ProjectX_sample/Aspx/Common/testClientCallback.master
root/programs/VB/Samples/WebApp_sample/ProjectX_sample/Aspx/Common/testNest/rootMasterPage.master
root/programs/VB/Samples/WebApp_sample/ProjectX_sample/Aspx/Common/testScreen1.master
root/programs/VB/Samples/WebApp_sample/ProjectX_sample/Aspx/Common/testScreen2.master
root/programs/VB/Samples/WebApp_sample/ProjectX_sample/Aspx/Common/testScreenCtrl.master
root/programs/VB/Samples/WebApp_sample/ProjectX_sample/Aspx/start/menu.aspx
root/programs/VB/Samples/WebApp_sample/ProjectX_sample/Aspx/testFxLayerP/nest/testScreen1nest.aspx.vb
root/programs/VB/Samples/WebApp_sample/ProjectX_sample/Aspx/testFxLayerP/nest/testScreen2nest.aspx.vb
root/programs/VB/Samples/WebApp_sample/ProjectX_sample/Aspx/testFxLayerP/normal/testScreen1.aspx.vb
root/programs/VB/Samples/WebApp_sample/ProjectX_sample/Aspx/testFxLayerP/normal/testScreen2.aspx.vb
root/programs/VB/Samples/WebApp_sample/ProjectX_sample/Aspx/testFxLayerP/table/testGridView.aspx.vb
root/programs/VB/Samples/WebApp_sample/ProjectX_sample/Aspx/testFxLayerP/table/testListView.aspx.vb
root/programs/VB/Samples/WebApp_sample/ProjectX_sample/Aspx/testFxLayerP/table/testRepeater.aspx.vb
root/programs/VB/Samples/WebApp_sample/ProjectX_sample/Aspx/testFxLayerP/testDialogAtOnLoad.aspx.vb
root/programs/VB/Samples/WebApp_sample/ProjectX_sample/Aspx/testScreenCtrl/WebForm0.aspx.vb
root/programs/VB/Samples/WebApp_sample/ProjectX_sample/Aspx/testScreenCtrl/WebForm1.aspx.vb
root/programs/VB/Samples/WebApp_sample/ProjectX_sample/Aspx/testScreenCtrl/WebForm2.aspx.vb
root/programs/VB/Samples/WebApp_sample/ProjectX_sample/Aspx/testScreenCtrl/WebForm3.aspx.vb
root/programs/VB/Samples/WebApp_sample/ProjectX_sample/Aspx/testScreenCtrl/WebForm4.aspx.vb
root/programs/VB/Samples/WebApp_sample/ProjectX_sample/Aspx/testScreenCtrl/WebForm5.aspx.vb
root/programs/VB/Samples/WebApp_sample/ProjectX_sample/Framework/Js/common.js
root/programs/VB/Samples/WebApp_sample/ProjectX_sample/app.config

Modified following code to resolve the URL issue in the Framework
- Implemented ResolveServerUrl method to resolve URL issue of screen transition control, display window and error transition control components
- Modified the relative path in the custom controls for the ImageUrl property
- Modified default relative path of the sample application screens
- Modified the following to resolve the URL issue in the application
Resolved URL issue in the *.master and *.aspx pages of the application
- Modified relative path in the app.config file of the application
- Modified relative path in the *.aspx.cs files to resolve URL issue of display window and screen transition control components
- Modified the relative path in the Server.MapPath to resolve the specified directory path
- Implemented …

Merged the URL issue related files from the root_VS2013 to root for VB version.

---

root/programs/VB/Samples/WebApp_sample/ProjectX_sample/Aspx/testFxLayerP/nest/testScreen1nest.aspx.vb

Merged the missing url path changes in testScreen1nest.aspx.vb

Merged the missing code to resolve url issue from root_2013 to root

---

root/programs/C#/Samples/WebApp_sample/ProjectX_sample/Framework/Js/common.js
root/programs/VB/Samples/WebApp_sample/ProjectX_sample/Framework/Js/common.js

Fix of window.returnValue of javascript issue that is occurred by IFRAME of IE11 correspondance.

Fixed : "IE 11 ignores dialogWidth-Height" #74

---

root/programs/C#/Samples/WebApp_sample/ProjectX_sample/Framework/Js/common.js
root/programs/VB/Samples/WebApp_sample/ProjectX_sample/Framework/Js/common.js

As discussed [here](https://github.com/SymphonyTeleca/OpenTouryo/pull/103#issuecomment-197690065),
We have recreated the pull request with new feature branch.

Implemented code to resolve the progress dialog mask issue in IE9 or more and other browsers

---

root/programs/C#/Frameworks/Infrastructure/Business/Resources/MyBusinessApplicationExceptionMessageResource.Designer.cs
root/programs/VB/Samples/AsyncSvc_sample/TestAsyncSvc_Sample/app.config

- Added SAMPLE_ERROR method
- Modified the encoding style of FxSqlEncoding property from "shift_jis" to "utf-8"

Modified the following to complete the merge work

---

root/files/tools/DGenTemplates/_Screen_ConditionalSearch.aspx
root/files/tools/DGenTemplates/_Screen_ConditionalSearch.aspx.cs
root/files/tools/DGenTemplates/_Screen_ConditionalSearch.aspx.vb
root/files/tools/DGenTemplates/_Screen_Detail.aspx
root/files/tools/DGenTemplates/_Screen_Detail.aspx.cs
root/files/tools/DGenTemplates/_Screen_Detail.aspx.vb
root/files/tools/DGenTemplates/_Screen_SearchAndUpdate.aspx
root/files/tools/DGenTemplates/_Screen_SearchAndUpdate.aspx.cs
root/files/tools/DGenTemplates/_Screen_SearchAndUpdate.aspx.vb

Removed insert button and related code chunk from following files,
- root/files/tools/DGenTemplates/_Screen_ConditionalSearch.aspx
- root/files/tools/DGenTemplates/_Screen_ConditionalSearch.aspx.cs
- root/files/tools/DGenTemplates/_Screen_Detail.aspx
- root/files/tools/DGenTemplates/_Screen_Detail.aspx.cs
- root/files/tools/DGenTemplates/_Screen_SearchAndUpdate.aspx
- root/files/tools/DGenTemplates/_Screen_SearchAndUpdate.aspx.cs
- root/files/tools/DGenTemplates/_Screen_ConditionalSearch.aspx.vb
- root/files/tools/DGenTemplates/_Screen_Detail.aspx.vb
- root/files/tools/DGenTemplates/_Screen_SearchAndUpdate.aspx.vb

Data maintenance insert

---

root/files/tools/DGenTemplates/_Screen_ConditionalSearch.aspx
root/files/tools/DGenTemplates/_Screen_ConditionalSearch.aspx.cs
root/files/tools/DGenTemplates/_Screen_ConditionalSearch.aspx.vb
root/files/tools/DGenTemplates/_Screen_Detail.aspx
root/files/tools/DGenTemplates/_Screen_Detail.aspx.cs
root/files/tools/DGenTemplates/_Screen_Detail.aspx.vb
root/files/tools/DGenTemplates/_Screen_SearchAndUpdate.aspx
root/files/tools/DGenTemplates/_Screen_SearchAndUpdate.aspx.cs
root/files/tools/DGenTemplates/_Screen_SearchAndUpdate.aspx.vb
root/programs/C#/Frameworks/Infrastructure/Business/Business/_3TierEngine.cs
root/programs/C#/Frameworks/Infrastructure/Business/Common/_3TierParameterValue.cs
root/programs/C#/Frameworks/Tools/DPQuery_Tool/Form3.cs

<li>Modified the below Source Template (DGenTemplate) to call the update operation method only once</li>
1.  _Screen_Detail.aspx.cs
<li>Added new method UOC_UpdateRecordDM to below B layer class for handling multiple table update in single transaction and also new collection parameter is declared </li>
1.  _3TierEngine.cs 
2.  _3TierParameterValue.cs
<li>Modified the code to replace space in Table Names and column Names with underscore operator in below DPQuery_Tool Form </li>
1. Form3.cs

Data Maintenance update Operation

---

root/programs/C#/Samples/WebApp_sample/ProjectX_sample/Framework/Js/common.js

- Implemented cross-browser detection method, to suppress double transmission
- Created form submission flag, to suppress double transmission
- Removed unnecessary check condition
- Revised the comment according to the modified code

Implemented double transmission prevention feature for modern browsers

---

root/programs/C#/Samples/WebApp_sample/ProjectX_sample/Aspx/Common/sampleScreen.master
root/programs/C#/Samples/WebApp_sample/ProjectX_sample/Aspx/Common/testAspNetAjaxExtension_Separate.master
root/programs/C#/Samples/WebApp_sample/ProjectX_sample/Aspx/Common/testAspNetAjaxExtension_Single.master
root/programs/C#/Samples/WebApp_sample/ProjectX_sample/Aspx/Common/testBlankScreen.master
root/programs/C#/Samples/WebApp_sample/ProjectX_sample/Aspx/Common/testClientCallback.master
root/programs/C#/Samples/WebApp_sample/ProjectX_sample/Aspx/Common/testNest/rootMasterPage.master
root/programs/C#/Samples/WebApp_sample/ProjectX_sample/Aspx/Common/testScreen1.master
root/programs/C#/Samples/WebApp_sample/ProjectX_sample/Aspx/Common/testScreen2.master
root/programs/C#/Samples/WebApp_sample/ProjectX_sample/Aspx/Common/testScreenCtrl.master
root/programs/C#/Samples/WebApp_sample/ProjectX_sample/Framework/Js/common.js

- Removed code to prevent F1 event from master page. 
- Implemented code in JavaScript to prevent F1 key event.

Moved implementation that prevents F1 event to JavaScript file.

---

root/programs/C#/Samples/WebApp_sample/ProjectX_sample/Aspx/Common/sampleScreen.master
root/programs/C#/Samples/WebApp_sample/ProjectX_sample/Aspx/Common/testAspNetAjaxExtension_Separate.master
root/programs/C#/Samples/WebApp_sample/ProjectX_sample/Aspx/Common/testAspNetAjaxExtension_Single.master
root/programs/C#/Samples/WebApp_sample/ProjectX_sample/Aspx/Common/testBlankScreen.master
root/programs/C#/Samples/WebApp_sample/ProjectX_sample/Aspx/Common/testClientCallback.master
root/programs/C#/Samples/WebApp_sample/ProjectX_sample/Aspx/Common/testNest/rootMasterPage.master
root/programs/C#/Samples/WebApp_sample/ProjectX_sample/Aspx/Common/testScreen1.master
root/programs/C#/Samples/WebApp_sample/ProjectX_sample/Aspx/Common/testScreen2.master
root/programs/C#/Samples/WebApp_sample/ProjectX_sample/Aspx/Common/testScreenCtrl.master
root/programs/C#/Samples/WebApp_sample/ProjectX_sample/Framework/Js/common.js

- https://github.com/SymphonyTeleca/OpenTouryo/pull/119
- https://github.com/SymphonyTeleca/OpenTouryo/pull/120

Modernization of the common.js

---

root/files/tools/DGenTemplates/_Screen_ConditionalSearch.aspx.cs
root/files/tools/DGenTemplates/_Screen_SearchAndUpdate.aspx.cs
root/programs/C#/Frameworks/Infrastructure/Business/Business/_3TierEngine.cs

Modified following pages to implement batch update operation in single transaction,
1. Added UOC_gvwGridView1_PageIndexChanging function to handle Gridview Paging event in _Screen_ConditionalSearch.aspx.cs
2. Modified UOC_btnBatUpd_Click function to call DoBusinessLogic function in single transaction in _Screen_SearchAndUpdate.aspx.cs
3. Added UOC_gvwGridView1_PageIndexChanging function to handle Gridview Paging event in _Screen_SearchAndUpdate.aspx.cs
4. Commented this.gvwGridView1.AllowPaging = false; line of code in UOC_gvwGridView1_RowCommand function to enable paging in _Screen_SearchAndUpdate.aspx.cs
5. Implemented 'UOC_BatchUpdateDM' method to perform batch update in single transaction in _3TierEngine.cs

Implementated Data Maintenance Batch update Operation

---

root/files/tools/DGenTemplates/_Screen_SearchAndUpdate.aspx.cs

- Removed the unnecessary data table copy as suggested in review comment [#10](https://github.com/OpenTouryoProject/OpenTouryoDocuments/issues/10#issuecomment-220887665)

Modified the code to remove the two-step copy process of the data table

---

root/files/tools/DGenTemplates/_Screen_Detail.aspx.cs
root/files/tools/DGenTemplates/_Screen_SearchAndUpdate.aspx.cs
root/programs/C#/Frameworks/Infrastructure/Business/Business/_3TierEngine.cs

1. Modified UOC_btnDelete_Click event to process multiple table delete operation in single transaction in _Screen_Detail.aspx.cs
2. Added remarks above UOC_btnDelete_Click event as a guideline for developers to modify the code to set the table sequence appropriately for successful delete operation in _Screen_Detail.aspx.cs
3. Added remarks above UOC_btnBatUpd_Click event as a guideline for developers to modify the code to set the table sequence appropriately for successful delete operation in _Screen_SearchAndUpdate.aspx.cs
4. Removed the unnecessary data table copy as suggested in review comment in _Screen_SearchAndUpdate.aspx.cs
5. Implemented 'UOC_DeleteRecordDM' method to perform delete operation in single transaction in _3TierEngine.cs
6. Modified the code of 'UOC_BatchUpdateDM' …

Data Maintainance Delete and Batch Delete

---

root/files/tools/DGenTemplates/_Screen_ConditionalSearch.aspx.vb
root/files/tools/DGenTemplates/_Screen_Detail.aspx.vb
root/programs/VB/Frameworks/Infrastructure/Business/Business/_3TierEngine.vb
root/programs/VB/Frameworks/Infrastructure/Business/Common/_3TierParameterValue.vb

1. Added paging method to handle gridview paging in _Screen_ConditionalSearch.aspx.vb
2. Modified gridview selected index changing method to handle the grid view row selection during paging in _Screen_ConditionalSearch.aspx.vb
3. Modify the Source Templates to _Screen_Detail.aspx.vb call the DoBusinessLogic method only once
4. Added new method UOC_UpdateRecordDM in _3TierEngine.vb for handling multiple table update in single transaction
5. A new collection parameter is declared in _3TierParameterValue.vb
6. Modified the code to replace space in Table Names with underscore operator
7. Modified the code to replace space in column Names with underscore operator

Data Maintenance update Operation VB

---

root/programs/C#/Frameworks/Infrastructure/Public/Db/DamSqlSvr.cs

Merged the Set property from OpenTouryoTemplate to OpenTouryo

Merged the Set property from OpenTouryoTemplate to OpenTouryo

---

root/programs/C#/Samples/AsyncSvc_sample/AsyncSvc_sample/LayerB.cs
root/programs/C#/Samples/AsyncSvc_sample/TestAsyncSvc_Sample/app.config

- Corrected the default value of connection string to match with the service settings
- Implemented code that respond to various test cases, other than success state
- Implemented method to update the command of selected task.
- Moved the stop and abort values to configuration settings

Modified AsyncProcess sample to respond to various test cases.

---

root/programs/C#/Frameworks/Infrastructure/Business/AsyncProcessingService/LayerB.cs
root/programs/C#/Frameworks/Infrastructure/ServiceInterface/AsyncProcessingService/AsyncProcessingService.cs
root/programs/C#/Frameworks/Infrastructure/ServiceInterface/AsyncProcessingService/TMProtocolDefinition.xml
root/programs/C#/Frameworks/Infrastructure/ServiceInterface/AsyncProcessingService/app.config

- Corrected the default value of connection string and XML transmission setting.
- Implemented the following to enhance the Start and Stop behavior.
- Created '_isServiceException' property and 'SetServiceException' method in the service
- Created 'TestConnection' method in the business component
- Added stop and abort percentage values to configuration settings.

Implemented code to modify the behaviour of start and stop service.

---

root/programs/C#/Frameworks/Infrastructure/ServiceInterface/AsyncProcessingService/AsyncProcessingService.cs

Corrected the condition check while stopping the service.

Corrected the condition check while stopping the service.

---

root/files/tools/DGenTemplates/_Screen_SearchAndUpdate.aspx.vb
root/programs/VB/Frameworks/Infrastructure/Business/Business/_3TierEngine.vb

1. Modified UOC_btnBatUpd_Click function to call DoBusinessLogic function in single transaction in _Screen_SearchAndUpdate.aspx.vb
2. Added UOC_gvwGridView1_PageIndexChanging function to handle Gridview Paging event in _Screen_SearchAndUpdate.aspx.vb
3. Removed Me.gvwGridView1.AllowPaging = false; line of code in UOC_gvwGridView1_RowCommand function to enable paging in _Screen_SearchAndUpdate.aspx.vb
4. Implemented 'UOC_BatchUpdateDM' method to perform batch update in single transaction in _3TierEngine.vb

Data Maintenance Batch update in VB

---

root/files/tools/DGenTemplates/_Screen_Detail.aspx.vb
root/files/tools/DGenTemplates/_Screen_SearchAndUpdate.aspx.vb
root/programs/VB/Frameworks/Infrastructure/Business/Business/_3TierEngine.vb

1. Modified UOC_btnDelete_Click event to process multiple table delete operation in single transaction in _Screen_Detail.aspx.vb
2. Added remarks above UOC_btnDelete_Click event as a guideline for developers to modify the code to set the table sequence appropriately for successful delete operation in _Screen_Detail.aspx.vb
3. Added remarks above UOC_btnBatUpd_Click event as a guideline for developers to modify the code to set the table sequence appropriately for successful delete operation in _Screen_SearchAndUpdate.aspx.vb
5. Implemented 'UOC_DeleteRecordDM' method to perform delete operation in single transaction in _3TierEngine.vb
6. Modified the code of 'UOC_BatchUpdateDM' method to perform batch delete operation in single transaction in _3TierEngine.vb

Data Maintenance Delete and Batch Delete modifications in VB

---

root/programs/C#/Samples/WebApp_sample/ProjectX_sample/ProjectX_sample/ProjectX_sample.csproj

Modified ProjectX_Sample webapp version from 4.0 to 3.5 as per review comment.

Changed webapp version from 4.0 to 3.5 as per review comment.

---

root/files/tools/DGenTemplates/_Screen_ConditionalSearch.aspx.cs
root/files/tools/DGenTemplates/_Screen_SearchAndUpdate.aspx.cs
root/files/tools/DGenTemplates/_Screen_SearchAndUpdate.aspx.vb
root/programs/VB/Frameworks/Infrastructure/Business/Business/_3TierEngine.vb

1. Modified gridview selected index changing method to handle the grid view row selection during paging in _Screen_ConditionalSearch.aspx.cs
2.  Modified UOC_gvwGridView1_RowCommand to fix gridview row replacement issue in _Screen_SearchAndUpdate.aspx.cs.
3. Modified UOC_gvwGridView1_RowCommand to fix gridview row replacement issue in _Screen_SearchAndUpdate.aspx.vb.
4. Modified the code of 'UOC_BatchUpdateDM' method to perform batch delete operation in single transaction in _3TierEngine.vb

Fixed the issue of grid view row replacement.

---

root/programs/C#/Samples/WebApp_sample/ProjectX_sample/ProjectX_sample/Aspx/Common/sampleScreen.master
root/programs/C#/Samples/WebApp_sample/ProjectX_sample/ProjectX_sample/Aspx/Common/testAspNetAjaxExtension_Separate.master
root/programs/C#/Samples/WebApp_sample/ProjectX_sample/ProjectX_sample/Aspx/Common/testAspNetAjaxExtension_Single.master
root/programs/C#/Samples/WebApp_sample/ProjectX_sample/ProjectX_sample/Aspx/Common/testBlankScreen.master
root/programs/C#/Samples/WebApp_sample/ProjectX_sample/ProjectX_sample/Aspx/Common/testClientCallback.master
root/programs/C#/Samples/WebApp_sample/ProjectX_sample/ProjectX_sample/Aspx/Common/testNest/rootMasterPage.master
root/programs/C#/Samples/WebApp_sample/ProjectX_sample/ProjectX_sample/Aspx/Common/testScreen1.master
root/programs/C#/Samples/WebApp_sample/ProjectX_sample/ProjectX_sample/Aspx/Common/testScreen2.master
root/programs/C#/Samples/WebApp_sample/ProjectX_sample/ProjectX_sample/Aspx/Common/testScreenCtrl.master
root/programs/C#/Samples/WebApp_sample/ProjectX_sample/ProjectX_sample/Framework/Js/common.js

- Modified jQuery.get() to $.Ajax() method.
- Added cache property in the Ajax ping request to prevent the session timeout.

Fixed the session timeout prevention function in WebForms.

---

root/programs/VB/Samples/WebApp_sample/ProjectX_sample/App_Code/sample/Dao/LayerD.vb
root/programs/VB/Samples/WebApp_sample/ProjectX_sample/Aspx/Common/sampleControl.ascx.vb
root/programs/VB/Samples/WebApp_sample/ProjectX_sample/Aspx/Common/sampleScreen.master.vb
root/programs/VB/Samples/WebApp_sample/ProjectX_sample/Aspx/Common/testAspNetAjaxExtension_Separate.master.vb
root/programs/VB/Samples/WebApp_sample/ProjectX_sample/Aspx/Common/testAspNetAjaxExtension_Single.master.vb
root/programs/VB/Samples/WebApp_sample/ProjectX_sample/Aspx/Common/testBlankScreen.master.vb
root/programs/VB/Samples/WebApp_sample/ProjectX_sample/Aspx/Common/testClientCallback.master.vb
root/programs/VB/Samples/WebApp_sample/ProjectX_sample/Aspx/Common/testNest/branchMasterPage1.master.vb
root/programs/VB/Samples/WebApp_sample/ProjectX_sample/Aspx/Common/testNest/branchMasterPage2.master.vb
root/programs/VB/Samples/WebApp_sample/ProjectX_sample/Aspx/Common/testNest/noBaseMasterPage.master.vb
root/programs/VB/Samples/WebApp_sample/ProjectX_sample/Aspx/Common/testNest/rootMasterPage.master.vb
root/programs/VB/Samples/WebApp_sample/ProjectX_sample/Aspx/Common/testNest/testScreen1bmp1.master.vb
root/programs/VB/Samples/WebApp_sample/ProjectX_sample/Aspx/Common/testNest/testScreen1bmp2.master.vb
root/programs/VB/Samples/WebApp_sample/ProjectX_sample/Aspx/Common/testNest/testScreen2bmp1.master.vb
root/programs/VB/Samples/WebApp_sample/ProjectX_sample/Aspx/Common/testNest/testScreen2bmp2.master.vb
root/programs/VB/Samples/WebApp_sample/ProjectX_sample/Aspx/Common/testScreen1.master.vb
root/programs/VB/Samples/WebApp_sample/ProjectX_sample/Aspx/Common/testScreen2.master.vb
root/programs/VB/Samples/WebApp_sample/ProjectX_sample/Aspx/Common/testScreenCtrl.master.vb
root/programs/VB/Samples/WebApp_sample/ProjectX_sample/Aspx/sample/3Tier/ProductsConditionalSearch.aspx.vb
root/programs/VB/Samples/WebApp_sample/ProjectX_sample/Aspx/sample/crud/sampleScreen.aspx.vb
root/programs/VB/Samples/WebApp_sample/ProjectX_sample/Aspx/testPublic/testScreen.aspx.vb

Removed unwanted code(ByVal changes) from ProjectX_sample to reduce differences with other versions.

Removed unwanted code(ByVal changes) from ProjectX_sample to maintain consistency.

---

root/programs/C#/Frameworks/Infrastructure/Public/Resources/PublicExceptionMessageResource.Designer.cs
root/programs/C#/Frameworks/Infrastructure/Public/Resources/PublicExceptionMessageResource.resx

Modified Implemented string to implemented in PublicExceptionMessageResource file to maintain consistency with other versions.

Modified Implemented string to implemented in PublicExceptionMessageResource file
